#!/bin/bash
user=$("whoami")

if [ $user != "root" ] ; then
echo "RUN AS sudo "
fi ;
if [ $user = "root" ] ; then
    apt update && apt update && apt update
    apt install tar zip unzip wget live-build  debootstrap make binutils
    apt install tar zip unzip wget live-build  debootstrap make binutils
    apt install tar zip unzip wget live-build  debootstrap make binutils
    dpkg -i common/Amzy.deb
    echo "Environment is set fully !!; make sure you check by typing Apkg or Amzy"
    sleep 2
    clear
fi
